# -*- coding: utf-8 -*-
"""download_anime_sele.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVHA5u8cFJTjazh9Xu1pupDgMUFDEufO
"""

from  selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import csv
import time
chrome_options = Options()
chrome_options.add_experimental_option("detach", True)
import wget

chrome_options = Options()  
chrome_options.add_argument("--headless")

driver = webdriver.Chrome(executable_path= "C:\\Users\91865\Downloads\chromedriver_win32\chromedriver")
#driver.set_window_position(0, 0)
#driver.set_window_size(0, 0)

time.sleep(3)

driver.get("https://4anime.to/")
time.sleep(7)

driver.find_element_by_xpath("/html/body/div[1]/div/div/div/header/div[1]/header/label/i").click()
time.sleep(2)

ani = input("please input the anime (^_^) :   ")

driver.find_element_by_xpath("/html/body/div[1]/div/div/div/header/div[2]/div[1]/div/div[2]/form/input[1]").send_keys(ani)
time.sleep(1)

driver.find_element_by_xpath("/html/body/div[3]/div/div/div[1]/div/div/div/a").click()
time.sleep(1)

print(driver.find_element_by_xpath("/html/body/div[1]/div/div/section/div/div/div/div[2]/div[4]/div[1]/section/div/div/div/div/ul"))

i = int(driver.find_element_by_xpath("/html/body/div[1]/div/div/section/div/div/div/div[2]/div[4]/div[1]/section/div/div/div/div/ul/li[last()]").text)
print(f"please input the episode number between 1 and {i}")

numb = input("please input the episode number(if multiple episodes use space in between and 'all' for all the episodes):  ")

bulk_numb = numb.split()
print(bulk_numb)

time.sleep(2)
if numb.lower() == 'all':
  length = i
else:
  length = len(bulk_numb)
  for j in range(0,length):
      driver.find_element_by_xpath("/html/body/div[1]/div/div/section/div/div/div/div[2]/div[4]/div[1]/section/div/div/div/div/ul/li[%s]" %bulk_numb[j]).click()
      time.sleep(0.5)
      video = driver.find_element_by_xpath("/html/body/div[1]/div/div[1]/section/div/div[2]/div/div[1]/div/div")
      link = video.get_attribute("src")
      driver.get(link)
      finall = wget.download(link)
      print(finall)



      time.sleep(5)
      driver.back()
      driver.back()
      time.sleep(3)

